<?php

use App\Entities\Country\Country;
use App\Entities\Currency\Currency;

class CountriesTableSeeder extends AbstractSeeder
{
    protected $truncateTables = [
        CreateCountriesTable::TABLENAME
    ];

    public function __construct(Country $model)
    {
        $this->model = $model;

        $this->itemList = [
            ['iso_code' => 'AF', 'name' => 'Afghanistan', 'currency_id' => $this->getCurrencyId('AFN')],
            ['iso_code' => 'AX', 'name' => 'Åland Islands', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'AL', 'name' => 'Albania', 'currency_id' => $this->getCurrencyId('ALL')],
            ['iso_code' => 'DZ', 'name' => 'Algeria', 'currency_id' => $this->getCurrencyId('DZD')],
            ['iso_code' => 'AS', 'name' => 'American Samoa', 'currency_id' => $this->getCurrencyId('USD')],
            ['iso_code' => 'AD', 'name' => 'Andorra', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'AO', 'name' => 'Angola', 'currency_id' => $this->getCurrencyId('AOA')],
            ['iso_code' => 'AI', 'name' => 'Anguilla', 'currency_id' => $this->getCurrencyId('XCD')],
            ['iso_code' => 'AQ', 'name' => 'Antarctica'],
            ['iso_code' => 'AG', 'name' => 'Antigua and Barbuda', 'currency_id' => $this->getCurrencyId('XCD')],
            ['iso_code' => 'AR', 'name' => 'Argentina', 'currency_id' => $this->getCurrencyId('ARS')],
            ['iso_code' => 'AM', 'name' => 'Armenia', 'currency_id' => $this->getCurrencyId('AMD')],
            ['iso_code' => 'AW', 'name' => 'Aruba', 'currency_id' => $this->getCurrencyId('AWG')],
            ['iso_code' => 'AU', 'name' => 'Australia', 'currency_id' => $this->getCurrencyId('AUD')],
            ['iso_code' => 'AT', 'name' => 'Austria', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'AZ', 'name' => 'Azerbaijan', 'currency_id' => $this->getCurrencyId('AZN')],
            ['iso_code' => 'BS', 'name' => 'Bahamas', 'currency_id' => $this->getCurrencyId('BSD')],
            ['iso_code' => 'BH', 'name' => 'Bahrain', 'currency_id' => $this->getCurrencyId('BHD')],
            ['iso_code' => 'BD', 'name' => 'Bangladesh', 'currency_id' => $this->getCurrencyId('BDT')],
            ['iso_code' => 'BB', 'name' => 'Barbados', 'currency_id' => $this->getCurrencyId('BBD')],
            ['iso_code' => 'BY', 'name' => 'Belarus', 'currency_id' => $this->getCurrencyId('BYR')],
            ['iso_code' => 'BE', 'name' => 'Belgium', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'BZ', 'name' => 'Belize', 'currency_id' => $this->getCurrencyId('BZD')],
            ['iso_code' => 'BJ', 'name' => 'Benin', 'currency_id' => $this->getCurrencyId('XOF')],
            ['iso_code' => 'BM', 'name' => 'Bermuda', 'currency_id' => $this->getCurrencyId('BMD')],
            ['iso_code' => 'BT', 'name' => 'Bhutan', 'currency_id' => $this->getCurrencyId('BTN')],
            ['iso_code' => 'BO', 'name' => 'Bolivia', 'currency_id' => $this->getCurrencyId('BOB')],
            ['iso_code' => 'BQ', 'name' => 'Bonaire, Sint Eustatius and Saba', 'currency_id' => $this->getCurrencyId('USD')],
            ['iso_code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'currency_id' => $this->getCurrencyId('BAM')],
            ['iso_code' => 'BW', 'name' => 'Botswana', 'currency_id' => $this->getCurrencyId('BWP')],
            ['iso_code' => 'BV', 'name' => 'Bouvet Island', 'currency_id' => $this->getCurrencyId('NOK')],
            ['iso_code' => 'BR', 'name' => 'Brazil', 'currency_id' => $this->getCurrencyId('BRL')],
            ['iso_code' => 'IO', 'name' => 'British Indian Ocean Territory', 'currency_id' => $this->getCurrencyId('GBP')],
            ['iso_code' => 'BN', 'name' => 'Brunei Darussalam', 'currency_id' => $this->getCurrencyId('BND')],
            ['iso_code' => 'BG', 'name' => 'Bulgaria', 'currency_id' => $this->getCurrencyId('BGN')],
            ['iso_code' => 'BF', 'name' => 'Burkina Faso', 'currency_id' => $this->getCurrencyId('XOF')],
            ['iso_code' => 'BI', 'name' => 'Burundi', 'currency_id' => $this->getCurrencyId('BIF')],
            ['iso_code' => 'KH', 'name' => 'Cambodia', 'currency_id' => $this->getCurrencyId('KHR')],
            ['iso_code' => 'CM', 'name' => 'Cameroon', 'currency_id' => $this->getCurrencyId('XAF')],
            ['iso_code' => 'CA', 'name' => 'Canada', 'currency_id' => $this->getCurrencyId('CAD')],
            ['iso_code' => 'CV', 'name' => 'Cape Verde', 'currency_id' => $this->getCurrencyId('CVE')],
            ['iso_code' => 'KY', 'name' => 'Cayman Islands', 'currency_id' => $this->getCurrencyId('KYD')],
            ['iso_code' => 'CF', 'name' => 'Central African Republic', 'currency_id' => $this->getCurrencyId('XAF')],
            ['iso_code' => 'TD', 'name' => 'Chad', 'currency_id' => $this->getCurrencyId('XAF')],
            ['iso_code' => 'CL', 'name' => 'Chile', 'currency_id' => $this->getCurrencyId('CLP')],
            ['iso_code' => 'CN', 'name' => 'China', 'currency_id' => $this->getCurrencyId('CNY')],
            ['iso_code' => 'CX', 'name' => 'Christmas Island', 'currency_id' => $this->getCurrencyId('AUD')],
            ['iso_code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'currency_id' => $this->getCurrencyId('AUD')],
            ['iso_code' => 'CO', 'name' => 'Colombia', 'currency_id' => $this->getCurrencyId('COP')],
            ['iso_code' => 'KM', 'name' => 'Comoros', 'currency_id' => $this->getCurrencyId('KMF')],
            ['iso_code' => 'CG', 'name' => 'Congo', 'currency_id' => $this->getCurrencyId('XAF')],
            ['iso_code' => 'CD', 'name' => 'Congo, The Democratic Republic of the', 'currency_id' => $this->getCurrencyId('CDF')],
            ['iso_code' => 'CK', 'name' => 'Cook Islands', 'currency_id' => $this->getCurrencyId('NZD')],
            ['iso_code' => 'CR', 'name' => 'Costa Rica', 'currency_id' => $this->getCurrencyId('CRC')],
            ['iso_code' => 'CI', 'name' => 'Côte d\'Ivoire', 'currency_id' => $this->getCurrencyId('XOF')],
            ['iso_code' => 'HR', 'name' => 'Croatia', 'currency_id' => $this->getCurrencyId('HRK')],
            ['iso_code' => 'CU', 'name' => 'Cuba', 'currency_id' => $this->getCurrencyId('CUP')],
            ['iso_code' => 'CW', 'name' => 'Curaçao', 'currency_id' => $this->getCurrencyId('ANG')],
            ['iso_code' => 'CY', 'name' => 'Cyprus', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'CZ', 'name' => 'Czech Republic', 'currency_id' => $this->getCurrencyId('CZK')],
            ['iso_code' => 'DK', 'name' => 'Denmark', 'currency_id' => $this->getCurrencyId('DKK')],
            ['iso_code' => 'DJ', 'name' => 'Djibouti', 'currency_id' => $this->getCurrencyId('DJF')],
            ['iso_code' => 'DM', 'name' => 'Dominica', 'currency_id' => $this->getCurrencyId('XCD')],
            ['iso_code' => 'DO', 'name' => 'Dominican Republic', 'currency_id' => $this->getCurrencyId('DOP')],
            ['iso_code' => 'EC', 'name' => 'Ecuador', 'currency_id' => $this->getCurrencyId('USD')],
            ['iso_code' => 'EG', 'name' => 'Egypt', 'currency_id' => $this->getCurrencyId('EGP')],
            ['iso_code' => 'SV', 'name' => 'El Salvador', 'currency_id' => $this->getCurrencyId('SVC')],
            ['iso_code' => 'GQ', 'name' => 'Equatorial Guinea', 'currency_id' => $this->getCurrencyId('XAF')],
            ['iso_code' => 'ER', 'name' => 'Eritrea', 'currency_id' => $this->getCurrencyId('ERN')],
            ['iso_code' => 'EE', 'name' => 'Estonia', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'ET', 'name' => 'Ethiopia', 'currency_id' => $this->getCurrencyId('ETB')],
            ['iso_code' => 'FK', 'name' => 'Falkland Islands (Malvinas)', 'currency_id' => $this->getCurrencyId('FKP')],
            ['iso_code' => 'FO', 'name' => 'Faroe Islands', 'currency_id' => $this->getCurrencyId('DKK')],
            ['iso_code' => 'FJ', 'name' => 'Fiji', 'currency_id' => $this->getCurrencyId('FJD')],
            ['iso_code' => 'FI', 'name' => 'Finland', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'FR', 'name' => 'France', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'GF', 'name' => 'French Guiana', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'PF', 'name' => 'French Polynesia', 'currency_id' => $this->getCurrencyId('XPF')],
            ['iso_code' => 'TF', 'name' => 'French Southern Territories', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'GA', 'name' => 'Gabon', 'currency_id' => $this->getCurrencyId('XAF')],
            ['iso_code' => 'GM', 'name' => 'Gambia', 'currency_id' => $this->getCurrencyId('GMD')],
            ['iso_code' => 'GE', 'name' => 'Georgia', 'currency_id' => $this->getCurrencyId('GEL')],
            ['iso_code' => 'DE', 'name' => 'Germany', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'GH', 'name' => 'Ghana', 'currency_id' => $this->getCurrencyId('GHS')],
            ['iso_code' => 'GI', 'name' => 'Gibraltar', 'currency_id' => $this->getCurrencyId('GIP')],
            ['iso_code' => 'GR', 'name' => 'Greece', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'GL', 'name' => 'Greenland', 'currency_id' => $this->getCurrencyId('DKK')],
            ['iso_code' => 'GD', 'name' => 'Grenada', 'currency_id' => $this->getCurrencyId('XCD')],
            ['iso_code' => 'GP', 'name' => 'Guadeloupe', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'GU', 'name' => 'Guam', 'currency_id' => $this->getCurrencyId('USD')],
            ['iso_code' => 'GT', 'name' => 'Guatemala', 'currency_id' => $this->getCurrencyId('GTQ')],
            ['iso_code' => 'GG', 'name' => 'Guernsey', 'currency_id' => $this->getCurrencyId('GBP')],
            ['iso_code' => 'GN', 'name' => 'Guinea', 'currency_id' => $this->getCurrencyId('GNF')],
            ['iso_code' => 'GW', 'name' => 'Guinea-Bissau', 'currency_id' => $this->getCurrencyId('XOF')],
            ['iso_code' => 'GY', 'name' => 'Guyana', 'currency_id' => $this->getCurrencyId('GYD')],
            ['iso_code' => 'HT', 'name' => 'Haiti', 'currency_id' => $this->getCurrencyId('HTG')],
            ['iso_code' => 'HM', 'name' => 'Heard Island and McDonald Islands', 'currency_id' => $this->getCurrencyId('AUD')],
            ['iso_code' => 'VA', 'name' => 'Holy See (Vatican City State)', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'HN', 'name' => 'Honduras', 'currency_id' => $this->getCurrencyId('HNL')],
            ['iso_code' => 'HK', 'name' => 'Hong Kong', 'currency_id' => $this->getCurrencyId('HKD')],
            ['iso_code' => 'HU', 'name' => 'Hungary', 'currency_id' => $this->getCurrencyId('HUF')],
            ['iso_code' => 'IS', 'name' => 'Iceland', 'currency_id' => $this->getCurrencyId('ISK')],
            ['iso_code' => 'IN', 'name' => 'India', 'currency_id' => $this->getCurrencyId('INR')],
            ['iso_code' => 'ID', 'name' => 'Indonesia', 'currency_id' => $this->getCurrencyId('IDR')],
            ['iso_code' => 'IR', 'name' => 'Iran, Islamic Republic of', 'currency_id' => $this->getCurrencyId('IRR')],
            ['iso_code' => 'IQ', 'name' => 'Iraq', 'currency_id' => $this->getCurrencyId('IQD')],
            ['iso_code' => 'IE', 'name' => 'Ireland', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'IM', 'name' => 'Isle of Man', 'currency_id' => $this->getCurrencyId('GBP')],
            ['iso_code' => 'IL', 'name' => 'Israel', 'currency_id' => $this->getCurrencyId('ILS')],
            ['iso_code' => 'IT', 'name' => 'Italy', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'JM', 'name' => 'Jamaica', 'currency_id' => $this->getCurrencyId('JMD')],
            ['iso_code' => 'JP', 'name' => 'Japan', 'currency_id' => $this->getCurrencyId('JPY')],
            ['iso_code' => 'JE', 'name' => 'Jersey', 'currency_id' => $this->getCurrencyId('GBP')],
            ['iso_code' => 'JO', 'name' => 'Jordan', 'currency_id' => $this->getCurrencyId('JOD')],
            ['iso_code' => 'KZ', 'name' => 'Kazakhstan', 'currency_id' => $this->getCurrencyId('KZT')],
            ['iso_code' => 'KE', 'name' => 'Kenya', 'currency_id' => $this->getCurrencyId('KES')],
            ['iso_code' => 'KI', 'name' => 'Kiribati', 'currency_id' => $this->getCurrencyId('AUD')],
            ['iso_code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of', 'currency_id' => $this->getCurrencyId('KPW')],
            ['iso_code' => 'KR', 'name' => 'Korea, Republic of', 'currency_id' => $this->getCurrencyId('KRW')],
            ['iso_code' => 'KW', 'name' => 'Kuwait', 'currency_id' => $this->getCurrencyId('KWD')],
            ['iso_code' => 'KG', 'name' => 'Kyrgyzstan', 'currency_id' => $this->getCurrencyId('KGS')],
            ['iso_code' => 'LA', 'name' => 'Lao People\'s Democratic Republic', 'currency_id' => $this->getCurrencyId('LAK')],
            ['iso_code' => 'LV', 'name' => 'Latvia', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'LB', 'name' => 'Lebanon', 'currency_id' => $this->getCurrencyId('LBP')],
            ['iso_code' => 'LS', 'name' => 'Lesotho', 'currency_id' => $this->getCurrencyId('LSL')],
            ['iso_code' => 'LR', 'name' => 'Liberia', 'currency_id' => $this->getCurrencyId('LRD')],
            ['iso_code' => 'LY', 'name' => 'Libya', 'currency_id' => $this->getCurrencyId('LYD')],
            ['iso_code' => 'LI', 'name' => 'Liechtenstein', 'currency_id' => $this->getCurrencyId('CHF')],
            ['iso_code' => 'LT', 'name' => 'Lithuania', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'LU', 'name' => 'Luxembourg', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'MO', 'name' => 'Macao', 'currency_id' => $this->getCurrencyId('MOP')],
            ['iso_code' => 'MK', 'name' => 'Macedonia, Republic of', 'currency_id' => $this->getCurrencyId('MKD')],
            ['iso_code' => 'MG', 'name' => 'Madagascar', 'currency_id' => $this->getCurrencyId('MGA')],
            ['iso_code' => 'MW', 'name' => 'Malawi', 'currency_id' => $this->getCurrencyId('MWK')],
            ['iso_code' => 'MY', 'name' => 'Malaysia', 'currency_id' => $this->getCurrencyId('MYR')],
            ['iso_code' => 'MV', 'name' => 'Maldives', 'currency_id' => $this->getCurrencyId('MVR')],
            ['iso_code' => 'ML', 'name' => 'Mali', 'currency_id' => $this->getCurrencyId('XOF')],
            ['iso_code' => 'MT', 'name' => 'Malta', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'MH', 'name' => 'Marshall Islands', 'currency_id' => $this->getCurrencyId('USD')],
            ['iso_code' => 'MQ', 'name' => 'Martinique', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'MR', 'name' => 'Mauritania', 'currency_id' => $this->getCurrencyId('MRO')],
            ['iso_code' => 'MU', 'name' => 'Mauritius', 'currency_id' => $this->getCurrencyId('MUR')],
            ['iso_code' => 'YT', 'name' => 'Mayotte', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'MX', 'name' => 'Mexico', 'currency_id' => $this->getCurrencyId('MXN')],
            ['iso_code' => 'FM', 'name' => 'Micronesia, Federated States of', 'currency_id' => $this->getCurrencyId('USD')],
            ['iso_code' => 'MD', 'name' => 'Moldova', 'currency_id' => $this->getCurrencyId('MDL')],
            ['iso_code' => 'MC', 'name' => 'Monaco', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'MN', 'name' => 'Mongolia', 'currency_id' => $this->getCurrencyId('MNT')],
            ['iso_code' => 'ME', 'name' => 'Montenegro', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'MS', 'name' => 'Montserrat', 'currency_id' => $this->getCurrencyId('XCD')],
            ['iso_code' => 'MA', 'name' => 'Morocco', 'currency_id' => $this->getCurrencyId('MAD')],
            ['iso_code' => 'MZ', 'name' => 'Mozambique', 'currency_id' => $this->getCurrencyId('MZN')],
            ['iso_code' => 'MM', 'name' => 'Myanmar', 'currency_id' => $this->getCurrencyId('MMK')],
            ['iso_code' => 'NA', 'name' => 'Namibia', 'currency_id' => $this->getCurrencyId('NAD')],
            ['iso_code' => 'NR', 'name' => 'Nauru', 'currency_id' => $this->getCurrencyId('AUD')],
            ['iso_code' => 'NP', 'name' => 'Nepal', 'currency_id' => $this->getCurrencyId('NPR')],
            ['iso_code' => 'NL', 'name' => 'Netherlands', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'NC', 'name' => 'New Caledonia', 'currency_id' => $this->getCurrencyId('XPF')],
            ['iso_code' => 'NZ', 'name' => 'New Zealand', 'currency_id' => $this->getCurrencyId('NZD')],
            ['iso_code' => 'NI', 'name' => 'Nicaragua', 'currency_id' => $this->getCurrencyId('NIO')],
            ['iso_code' => 'NE', 'name' => 'Niger', 'currency_id' => $this->getCurrencyId('XOF')],
            ['iso_code' => 'NG', 'name' => 'Nigeria', 'currency_id' => $this->getCurrencyId('NGN')],
            ['iso_code' => 'NU', 'name' => 'Niue', 'currency_id' => $this->getCurrencyId('NZD')],
            ['iso_code' => 'NF', 'name' => 'Norfolk Island', 'currency_id' => $this->getCurrencyId('AUD')],
            ['iso_code' => 'MP', 'name' => 'Northern Mariana Islands', 'currency_id' => $this->getCurrencyId('USD')],
            ['iso_code' => 'NO', 'name' => 'Norway', 'currency_id' => $this->getCurrencyId('NOK')],
            ['iso_code' => 'OM', 'name' => 'Oman', 'currency_id' => $this->getCurrencyId('OMR')],
            ['iso_code' => 'PK', 'name' => 'Pakistan', 'currency_id' => $this->getCurrencyId('PKR')],
            ['iso_code' => 'PW', 'name' => 'Palau', 'currency_id' => $this->getCurrencyId('USD')],
            ['iso_code' => 'PS', 'name' => 'Palestine, State of', 'currency_id' => $this->getCurrencyId('ILS')],
            ['iso_code' => 'PA', 'name' => 'Panama', 'currency_id' => $this->getCurrencyId('PAB')],
            ['iso_code' => 'PG', 'name' => 'Papua New Guinea', 'currency_id' => $this->getCurrencyId('PGK')],
            ['iso_code' => 'PY', 'name' => 'Paraguay', 'currency_id' => $this->getCurrencyId('PYG')],
            ['iso_code' => 'PE', 'name' => 'Peru', 'currency_id' => $this->getCurrencyId('PEN')],
            ['iso_code' => 'PH', 'name' => 'Philippines', 'currency_id' => $this->getCurrencyId('PHP')],
            ['iso_code' => 'PN', 'name' => 'Pitcairn', 'currency_id' => $this->getCurrencyId('NZD')],
            ['iso_code' => 'PL', 'name' => 'Poland', 'currency_id' => $this->getCurrencyId('PLN')],
            ['iso_code' => 'PT', 'name' => 'Portugal', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'PR', 'name' => 'Puerto Rico', 'currency_id' => $this->getCurrencyId('USD')],
            ['iso_code' => 'QA', 'name' => 'Qatar', 'currency_id' => $this->getCurrencyId('QAR')],
            ['iso_code' => 'RE', 'name' => 'Réunion', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'RO', 'name' => 'Romania', 'currency_id' => $this->getCurrencyId('RON')],
            ['iso_code' => 'RU', 'name' => 'Russian Federation', 'currency_id' => $this->getCurrencyId('RUB')],
            ['iso_code' => 'RW', 'name' => 'Rwanda', 'currency_id' => $this->getCurrencyId('RWF')],
            ['iso_code' => 'BL', 'name' => 'Saint Barthélemy', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'SH', 'name' => 'Saint Helena, Ascension and Tristan da Cunha', 'currency_id' => $this->getCurrencyId('SHP')],
            ['iso_code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'currency_id' => $this->getCurrencyId('XCD')],
            ['iso_code' => 'LC', 'name' => 'Saint Lucia', 'currency_id' => $this->getCurrencyId('XCD')],
            ['iso_code' => 'MF', 'name' => 'Saint Martin (French part)', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'currency_id' => $this->getCurrencyId('XCD')],
            ['iso_code' => 'WS', 'name' => 'Samoa', 'currency_id' => $this->getCurrencyId('WST')],
            ['iso_code' => 'SM', 'name' => 'San Marino', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'ST', 'name' => 'São Tomé and Príncipe', 'currency_id' => $this->getCurrencyId('STD')],
            ['iso_code' => 'SA', 'name' => 'Saudi Arabia', 'currency_id' => $this->getCurrencyId('SAR')],
            ['iso_code' => 'SN', 'name' => 'Senegal', 'currency_id' => $this->getCurrencyId('XOF')],
            ['iso_code' => 'RS', 'name' => 'Serbia', 'currency_id' => $this->getCurrencyId('RSD')],
            ['iso_code' => 'SC', 'name' => 'Seychelles', 'currency_id' => $this->getCurrencyId('SCR')],
            ['iso_code' => 'SL', 'name' => 'Sierra Leone', 'currency_id' => $this->getCurrencyId('SLL')],
            ['iso_code' => 'SG', 'name' => 'Singapore', 'currency_id' => $this->getCurrencyId('SGD')],
            ['iso_code' => 'SX', 'name' => 'Sint Maarten (Dutch part)', 'currency_id' => $this->getCurrencyId('ANG')],
            ['iso_code' => 'SK', 'name' => 'Slovakia', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'SI', 'name' => 'Slovenia', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'SB', 'name' => 'Solomon Islands', 'currency_id' => $this->getCurrencyId('SBD')],
            ['iso_code' => 'SO', 'name' => 'Somalia', 'currency_id' => $this->getCurrencyId('SOS')],
            ['iso_code' => 'ZA', 'name' => 'South Africa', 'currency_id' => $this->getCurrencyId('ZAR')],
            ['iso_code' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands', 'currency_id' => $this->getCurrencyId('GBP')],
            ['iso_code' => 'ES', 'name' => 'Spain', 'currency_id' => $this->getCurrencyId('EUR')],
            ['iso_code' => 'LK', 'name' => 'Sri Lanka', 'currency_id' => $this->getCurrencyId('LKR')],
            ['iso_code' => 'SD', 'name' => 'Sudan', 'currency_id' => $this->getCurrencyId('SDG')],
            ['iso_code' => 'SR', 'name' => 'Suriname', 'currency_id' => $this->getCurrencyId('SRD')],
            ['iso_code' => 'SS', 'name' => 'South Sudan', 'currency_id' => $this->getCurrencyId('SSP')],
            ['iso_code' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 'currency_id' => $this->getCurrencyId('NOK')],
            ['iso_code' => 'SZ', 'name' => 'Swaziland', 'currency_id' => $this->getCurrencyId('SZL')],
            ['iso_code' => 'SE', 'name' => 'Sweden', 'currency_id' => $this->getCurrencyId('SEK')],
            ['iso_code' => 'CH', 'name' => 'Switzerland', 'currency_id' => $this->getCurrencyId('CHF')],
            ['iso_code' => 'SY', 'name' => 'Syrian Arab Republic', 'currency_id' => $this->getCurrencyId('SYP')],
            ['iso_code' => 'TW', 'name' => 'Taiwan', 'currency_id' => $this->getCurrencyId('TWD')],
            ['iso_code' => 'TJ', 'name' => 'Tajikistan', 'currency_id' => $this->getCurrencyId('TJS')],
            ['iso_code' => 'TZ', 'name' => 'Tanzania', 'currency_id' => $this->getCurrencyId('TZS')],
            ['iso_code' => 'TH', 'name' => 'Thailand', 'currency_id' => $this->getCurrencyId('THB')],
            ['iso_code' => 'TL', 'name' => 'Timor-Leste', 'currency_id' => $this->getCurrencyId('USD')],
            ['iso_code' => 'TG', 'name' => 'Togo', 'currency_id' => $this->getCurrencyId('XOF')],
            ['iso_code' => 'TK', 'name' => 'Tokelau', 'currency_id' => $this->getCurrencyId('NZD')],
            ['iso_code' => 'TO', 'name' => 'Tonga', 'currency_id' => $this->getCurrencyId('TOP')],
            ['iso_code' => 'TT', 'name' => 'Trinidad and Tobago', 'currency_id' => $this->getCurrencyId('TTD')],
            ['iso_code' => 'TN', 'name' => 'Tunisia', 'currency_id' => $this->getCurrencyId('TND')],
            ['iso_code' => 'TR', 'name' => 'Turkey', 'currency_id' => $this->getCurrencyId('TRY')],
            ['iso_code' => 'TM', 'name' => 'Turkmenistan', 'currency_id' => $this->getCurrencyId('TMT')],
            ['iso_code' => 'TC', 'name' => 'Turks and Caicos Islands', 'currency_id' => $this->getCurrencyId('USD')],
            ['iso_code' => 'TV', 'name' => 'Tuvalu', 'currency_id' => $this->getCurrencyId('AUD')],
            ['iso_code' => 'UG', 'name' => 'Uganda', 'currency_id' => $this->getCurrencyId('UGX')],
            ['iso_code' => 'UA', 'name' => 'Ukraine', 'currency_id' => $this->getCurrencyId('UAH')],
            ['iso_code' => 'AE', 'name' => 'United Arab Emirates', 'currency_id' => $this->getCurrencyId('AED')],
            ['iso_code' => 'GB', 'name' => 'United Kingdom', 'currency_id' => $this->getCurrencyId('GBP')],
            ['iso_code' => 'US', 'name' => 'United States', 'currency_id' => $this->getCurrencyId('USD')],
            ['iso_code' => 'UM', 'name' => 'United States Minor Outlying Islands', 'currency_id' => $this->getCurrencyId('USD')],
            ['iso_code' => 'UY', 'name' => 'Uruguay', 'currency_id' => $this->getCurrencyId('UYU')],
            ['iso_code' => 'UZ', 'name' => 'Uzbekistan', 'currency_id' => $this->getCurrencyId('UZS')],
            ['iso_code' => 'VU', 'name' => 'Vanuatu', 'currency_id' => $this->getCurrencyId('VUV')],
            ['iso_code' => 'VE', 'name' => 'Venezuela', 'currency_id' => $this->getCurrencyId('VEF')],
            ['iso_code' => 'VN', 'name' => 'Vietnam, Socialist Republic of', 'currency_id' => $this->getCurrencyId('VND')],
            ['iso_code' => 'VG', 'name' => 'Virgin Islands, British', 'currency_id' => $this->getCurrencyId('USD')],
            ['iso_code' => 'VI', 'name' => 'Virgin Islands, U.S.', 'currency_id' => $this->getCurrencyId('USD')],
            ['iso_code' => 'WF', 'name' => 'Wallis and Futuna', 'currency_id' => $this->getCurrencyId('XPF')],
            ['iso_code' => 'EH', 'name' => 'Western Sahara', 'currency_id' => $this->getCurrencyId('MAD')],
            ['iso_code' => 'YE', 'name' => 'Yemen', 'currency_id' => $this->getCurrencyId('YER')],
            ['iso_code' => 'ZM', 'name' => 'Zambia', 'currency_id' => $this->getCurrencyId('ZMW')],
            ['iso_code' => 'ZW', 'name' => 'Zimbabwe', 'currency_id' => $this->getCurrencyId('ZWD')],
        ];
    }

    /**
     * Find and set currency_id from specified ISO 4217 code.
     *
     * @param string $iso_code
     * @return null
     */
    public function getCurrencyId($iso_code)
    {
        if ($currency = Currency::where('iso_code', $iso_code)->first()) {
            return $currency->id;
        }

        return null;
    }
}
