<?php

use App\Entities\Language\Language;

class LanguagesTableSeeder extends AbstractSeeder
{
    protected $truncateTables = [
        CreateLanguagesTable::TABLENAME
    ];

    protected $itemList = [
        ['iso_code' => 'aa', 'name' => 'Qafar'],
        ['iso_code' => 'af', 'name' => 'Afrikaans'],
        ['iso_code' => 'ak', 'name' => 'Akan'],
        ['iso_code' => 'am', 'name' => 'አማርኛ', 'script' => 'Ethi'],
        ['iso_code' => 'an', 'name' => 'Aragonés'],
        ['iso_code' => 'ar', 'name' => '‏العربية‏', 'script' => 'Arab'],
        ['iso_code' => 'as', 'name' => 'অসমীয়া', 'script' => 'Beng'],
        ['iso_code' => 'ay', 'name' => 'Aymar aru'],
        ['iso_code' => 'az', 'name' => 'Azərbaycan dili'],
        ['iso_code' => 'be', 'name' => 'Беларуская', 'script' => 'Cyrl'],
        ['iso_code' => 'bg', 'name' => 'Български', 'script' => 'Cyrl'],
        ['iso_code' => 'bn', 'name' => 'বাংলা', 'script' => 'Beng'],
        ['iso_code' => 'bo', 'name' => 'ລາວ', 'script' => 'Tibt'],
        ['iso_code' => 'br', 'name' => 'Brezhoneg'],
        ['iso_code' => 'bs', 'name' => 'Bosanski'],
        ['iso_code' => 'ca', 'name' => 'Català'],
        ['iso_code' => 'ce', 'name' => 'нохчийн мотт', 'script' => 'Cyrl'],
        ['iso_code' => 'co', 'name' => 'Corsu'],
        ['iso_code' => 'cs', 'name' => 'Čeština'],
        ['iso_code' => 'cv', 'name' => 'чӑваш чӗлхи', 'script' => 'Cyrl'],
        ['iso_code' => 'cy', 'name' => 'Cymraeg'],
        ['iso_code' => 'da', 'name' => 'Dansk'],
        ['iso_code' => 'de', 'name' => 'Deutsch'],
        ['iso_code' => 'dv', 'name' => 'ދިވެހިބަސް', 'script' => 'Thaa'],
        ['iso_code' => 'dz', 'name' => 'རྫོང་ཁ', 'script' => 'Tibt'],
        ['iso_code' => 'el', 'name' => 'Ελληνικά', 'script' => 'Grek'],
        ['iso_code' => 'en', 'name' => 'English'],
        ['iso_code' => 'eo', 'name' => 'Esperanto'],
        ['iso_code' => 'es', 'name' => 'Español'],
        ['iso_code' => 'et', 'name' => 'Eesti'],
        ['iso_code' => 'eu', 'name' => 'Euskara'],
        ['iso_code' => 'fa', 'name' => '‏فارسی‏', 'script' => 'Arab'],
        ['iso_code' => 'ff', 'name' => 'Pulaar'],
        ['iso_code' => 'fi', 'name' => 'Suomi'],
        ['iso_code' => 'fo', 'name' => 'Føroyskt'],
        ['iso_code' => 'fr', 'name' => 'Français'],
        ['iso_code' => 'fy', 'name' => 'Frysk'],
        ['iso_code' => 'ga', 'name' => 'Gaeilge'],
        ['iso_code' => 'gd', 'name' => 'Gàidhlig'],
        ['iso_code' => 'gl', 'name' => 'Galego'],
        ['iso_code' => 'gn', 'name' => 'Guarani'],
        ['iso_code' => 'gu', 'name' => 'ગુજરાતી', 'script' => 'Gujr'],
        ['iso_code' => 'gv', 'name' => 'Gaelg'],
        ['iso_code' => 'ha', 'name' => 'Hausa'],
        ['iso_code' => 'he', 'name' => '‏עברית‏', 'script' => 'Hebr'],
        ['iso_code' => 'hi', 'name' => 'हिन्दी', 'script' => 'Deva'],
        ['iso_code' => 'hr', 'name' => 'Hrvatski'],
        ['iso_code' => 'ht', 'name' => 'Kreyòl Ayisyen'],
        ['iso_code' => 'hu', 'name' => 'Magyar'],
        ['iso_code' => 'hy', 'name' => 'Հայերեն', 'script' => 'Armn'],
        ['iso_code' => 'ia', 'name' => 'interlingua'],
        ['iso_code' => 'id', 'name' => 'Bahasa Indonesia'],
        ['iso_code' => 'ig', 'name' => 'Asụsụ Igbo'],
        ['iso_code' => 'ik', 'name' => 'Iñupiaq'],
        ['iso_code' => 'is', 'name' => 'Íslenska'],
        ['iso_code' => 'it', 'name' => 'Italiano'],
        ['iso_code' => 'iu', 'name' => 'ᐃᓄᒃᑎᑐᑦ', 'script' => 'Cans'],
        ['iso_code' => 'ja', 'name' => '日本語', 'script' => 'Jpan'],
        ['iso_code' => 'jv', 'name' => 'Basa Jawa'],
        ['iso_code' => 'ka', 'name' => 'ქართული', 'script' => 'Geor'],
        ['iso_code' => 'kk', 'name' => 'Қазақша', 'script' => 'Cyrl'],
        ['iso_code' => 'kl', 'name' => 'kalaallisut'],
        ['iso_code' => 'km', 'name' => 'ភាសាខ្មែរ', 'script' => 'Khmr'],
        ['iso_code' => 'kn', 'name' => 'ಕನ್ನಡ', 'script' => 'Knda'],
        ['iso_code' => 'ko', 'name' => '한국어', 'script' => 'Hang'],
        ['iso_code' => 'ks', 'name' => 'کأشُر', 'script' => 'Arab'],
        ['iso_code' => 'ku', 'name' => 'كوردی', 'script' => 'Arab'],
        ['iso_code' => 'kw', 'name' => 'kernewek'],
        ['iso_code' => 'ky', 'name' => 'кыргызча', 'script' => 'Cyrl'],
        ['iso_code' => 'la', 'name' => 'lingua latina'],
        ['iso_code' => 'lb', 'name' => 'Lëtzebuergesch'],
        ['iso_code' => 'lg', 'name' => 'Luganda'],
        ['iso_code' => 'li', 'name' => 'Limburgs'],
        ['iso_code' => 'ln', 'name' => 'Lingála'],
        ['iso_code' => 'lo', 'name' => 'ພາສາລາວ', 'script' => 'Laoo'],
        ['iso_code' => 'lt', 'name' => 'Lietuvių'],
        ['iso_code' => 'lv', 'name' => 'Latviešu'],
        ['iso_code' => 'mg', 'name' => 'Malagasy'],
        ['iso_code' => 'mh', 'name' => 'Kajin M̧ajeļ'],
        ['iso_code' => 'mi', 'name' => 'Te Reo Māori'],
        ['iso_code' => 'mk', 'name' => 'Македонски', 'script' => 'Cyrl'],
        ['iso_code' => 'ml', 'name' => 'മലയാളം', 'script' => 'Mlym'],
        ['iso_code' => 'mn', 'name' => 'Монгол', 'script' => 'Cyrl'],
        ['iso_code' => 'mr', 'name' => 'मराठी', 'script' => 'Deva'],
        ['iso_code' => 'ms', 'name' => 'Bahasa Melayu'],
        ['iso_code' => 'mt', 'name' => 'Malti'],
        ['iso_code' => 'my', 'name' => 'မြန်မာဘာသာ', 'script' => 'Mymr'],
        ['iso_code' => 'nb', 'name' => 'Norsk (bokmål)'],
        ['iso_code' => 'nd', 'name' => 'isiNdebele (Zimbabwe)'],
        ['iso_code' => 'ne', 'name' => 'नेपाली', 'script' => 'Deva'],
        ['iso_code' => 'nl', 'name' => 'Nederlands'],
        ['iso_code' => 'nn', 'name' => 'Norsk (nynorsk)'],
        ['iso_code' => 'nr', 'name' => 'isiNdebele (South Africa)'],
        ['iso_code' => 'ny', 'name' => 'Chichewa'],
        ['iso_code' => 'oc', 'name' => 'occitan'],
        ['iso_code' => 'om', 'name' => 'Oromoo'],
        ['iso_code' => 'or', 'name' => 'ଓଡ଼ିଆ', 'script' => 'Orya'],
        ['iso_code' => 'os', 'name' => 'Ирон', 'script' => 'Cyrl'],
        ['iso_code' => 'pa', 'name' => 'ਪੰਜਾਬੀ', 'script' => 'Guru'],
        ['iso_code' => 'pl', 'name' => 'Polski'],
        ['iso_code' => 'ps', 'name' => '‏پښتو‏', 'script' => 'Arab'],
        ['iso_code' => 'pt', 'name' => 'Português'],
        ['iso_code' => 'qu', 'name' => 'Qhichwa'],
        ['iso_code' => 'rm', 'name' => 'Rumantsch'],
        ['iso_code' => 'ro', 'name' => 'Română'],
        ['iso_code' => 'ru', 'name' => 'Русский', 'script' => 'Cyrl'],
        ['iso_code' => 'rw', 'name' => 'Ikinyarwanda'],
        ['iso_code' => 'sa', 'name' => 'संस्कृतम्', 'script' => 'Deva'],
        ['iso_code' => 'sc', 'name' => 'Sardu'],
        ['iso_code' => 'sd', 'name' => 'سنڌي', 'script' => 'Arab'],
        ['iso_code' => 'se', 'name' => 'Davvisámegiella'],
        ['iso_code' => 'si', 'name' => 'සිංහල', 'script' => 'Sinh'],
        ['iso_code' => 'sk', 'name' => 'Slovenčina'],
        ['iso_code' => 'sl', 'name' => 'Slovenščina'],
        ['iso_code' => 'sn', 'name' => 'Shona'],
        ['iso_code' => 'so', 'name' => 'Af-Soomaali'],
        ['iso_code' => 'sq', 'name' => 'Shqip'],
        ['iso_code' => 'sr', 'name' => 'Српски', 'script' => 'Cyrl'],
        ['iso_code' => 'ss', 'name' => 'SiSwati'],
        ['iso_code' => 'st', 'name' => 'Sesotho'],
        ['iso_code' => 'sv', 'name' => 'Svenska'],
        ['iso_code' => 'sw', 'name' => 'Kiswahili'],
        ['iso_code' => 'ta', 'name' => 'தமிழ்', 'script' => 'Taml'],
        ['iso_code' => 'te', 'name' => 'తెలుగు', 'script' => 'Telu'],
        ['iso_code' => 'tg', 'name' => 'Тоҷикӣ', 'script' => 'Cyrl'],
        ['iso_code' => 'th', 'name' => 'ภาษาไทย', 'script' => 'Thai'],
        ['iso_code' => 'ti', 'name' => 'ትግርኛ', 'script' => 'Ethi'],
        ['iso_code' => 'tk', 'name' => 'Түркмен', 'script' => 'Cyrl'],
        ['iso_code' => 'tl', 'name' => 'Tagalog'],
        ['iso_code' => 'tn', 'name' => 'Setswana'],
        ['iso_code' => 'tr', 'name' => 'Türkçe'],
        ['iso_code' => 'ts', 'name' => 'Xitsonga'],
        ['iso_code' => 'tt', 'name' => 'Татарча', 'script' => 'Cyrl'],
        ['iso_code' => 'ug', 'name' => 'ئۇيغۇرچە', 'script' => 'Arab'],
        ['iso_code' => 'uk', 'name' => 'Українська', 'script' => 'Cyrl'],
        ['iso_code' => 'ur', 'name' => '‏اردو‏', 'script' => 'Arab'],
        ['iso_code' => 'uz', 'name' => 'O\'zbek'],
        ['iso_code' => 've', 'name' => 'Tshivenḓa'],
        ['iso_code' => 'vi', 'name' => 'Tiếng Việt'],
        ['iso_code' => 'wa', 'name' => 'Walon'],
        ['iso_code' => 'wo', 'name' => 'Wolof'],
        ['iso_code' => 'xh', 'name' => 'isiXhosa'],
        ['iso_code' => 'yi', 'name' => '‏ייִדיש‏', 'script' => 'Hebr'],
        ['iso_code' => 'yo', 'name' => 'èdè Yorùbá'],
        ['iso_code' => 'zh', 'name' => '中文', 'script' => 'Hans'],
        ['iso_code' => 'zu', 'name' => 'isiZulu'],
    ];

    public function __construct(Language $model)
    {
        $this->model = $model;
    }
}
